package com.advco;

import java.util.*;

public class Day6 {
    public static void main(String[] args) {
        partTwo();
    }

    public static void partOne(){
        List<String> groups = Arrays.asList(PUZZLE_INPUT.split("\n\n"));
        int sumOfCount = 0;

        for(String group : groups){
            Map<Character, Boolean> answered = new HashMap<>();
            answered.put('a', false);
            answered.put('b', false);
            answered.put('c', false);
            answered.put('d', false);
            answered.put('e', false);
            answered.put('f', false);
            answered.put('g', false);
            answered.put('h', false);
            answered.put('i', false);
            answered.put('j', false);
            answered.put('k', false);
            answered.put('l', false);
            answered.put('m', false);
            answered.put('n', false);
            answered.put('o', false);
            answered.put('p', false);
            answered.put('q', false);
            answered.put('r', false);
            answered.put('s', false);
            answered.put('t', false);
            answered.put('u', false);
            answered.put('v', false);
            answered.put('w', false);
            answered.put('x', false);
            answered.put('y', false);
            answered.put('z', false);

            List<String> persons = Arrays.asList(group.split("\n"));

            for(String person : persons){
                for(int i = 0; i < person.length(); i++){
                    answered.put(person.charAt(i), true);
                }
            }

            Iterator<Boolean> iterator = answered.values().iterator();
            while(iterator.hasNext()){
                if(iterator.next() == true){
                    sumOfCount++;
                }
            }
        }

        System.out.println("sum of count: " + sumOfCount);
    }

    public static void partTwo(){
        List<String> groups = Arrays.asList(PUZZLE_INPUT.split("\n\n"));
        int sumOfCount = 0;

        for(String group : groups){
            Map<Character, Integer> answered = new HashMap<>();
            answered.put('a', 0);
            answered.put('b', 0);
            answered.put('c', 0);
            answered.put('d', 0);
            answered.put('e', 0);
            answered.put('f', 0);
            answered.put('g', 0);
            answered.put('h', 0);
            answered.put('i', 0);
            answered.put('j', 0);
            answered.put('k', 0);
            answered.put('l', 0);
            answered.put('m', 0);
            answered.put('n', 0);
            answered.put('o', 0);
            answered.put('p', 0);
            answered.put('q', 0);
            answered.put('r', 0);
            answered.put('s', 0);
            answered.put('t', 0);
            answered.put('u', 0);
            answered.put('v', 0);
            answered.put('w', 0);
            answered.put('x', 0);
            answered.put('y', 0);
            answered.put('z', 0);

            List<String> persons = Arrays.asList(group.split("\n"));

            for(String person : persons){
                for(int i = 0; i < person.length(); i++){
                    answered.put(person.charAt(i), answered.get(person.charAt(i))+1);
                }
            }

            Iterator<Integer> iterator = answered.values().iterator();
            while(iterator.hasNext()){
                if(iterator.next() == persons.size()){
                    sumOfCount++;
                }
            }
        }

        System.out.println("sum of count: " + sumOfCount);
    }

    public static final String PUZZLE_TEST = "abc\n" +
            "\n" +
            "a\n" +
            "b\n" +
            "c\n" +
            "\n" +
            "ab\n" +
            "ac\n" +
            "\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "a\n" +
            "\n" +
            "b";
    public static final String PUZZLE_INPUT = "wdcmlzfnugqtvjbsahi\n" +
            "easrkmocxbpjgi\n" +
            "\n" +
            "xrpnegqlcsyodhjfutzakmiwvb\n" +
            "mgilapxjtrndbheyqzckfouwsv\n" +
            "\n" +
            "scynhfozmlvbqkarwj\n" +
            "qhvjkmbyxcfonlazdw\n" +
            "vjhzfnapwclkqiomyb\n" +
            "\n" +
            "bpourq\n" +
            "ujpmoqs\n" +
            "obqup\n" +
            "\n" +
            "v\n" +
            "v\n" +
            "v\n" +
            "v\n" +
            "v\n" +
            "\n" +
            "hwjlda\n" +
            "thkdjo\n" +
            "mlhdjw\n" +
            "edyfjvh\n" +
            "djh\n" +
            "\n" +
            "xvjadplfcwmkeriug\n" +
            "adgtscyjipewvulr\n" +
            "\n" +
            "hmkipduz\n" +
            "mdzkupi\n" +
            "\n" +
            "vtyizwcdm\n" +
            "zdvtcyiwm\n" +
            "mfzcywvtid\n" +
            "iydclntzvmw\n" +
            "\n" +
            "ps\n" +
            "pm\n" +
            "pm\n" +
            "p\n" +
            "pm\n" +
            "\n" +
            "nglatdiw\n" +
            "twialgd\n" +
            "igsadtwl\n" +
            "iadgtwl\n" +
            "igawltd\n" +
            "\n" +
            "jqoxkavs\n" +
            "askoxvqj\n" +
            "aqjvxskho\n" +
            "javqkxso\n" +
            "kaxjoqsv\n" +
            "\n" +
            "ltkjfoxes\n" +
            "aifogkepx\n" +
            "ufcekybmzx\n" +
            "tigxeahnkf\n" +
            "\n" +
            "xzfqbsnhmrviju\n" +
            "rmfvsbihpujq\n" +
            "hstfumvgrobijq\n" +
            "\n" +
            "bga\n" +
            "ye\n" +
            "\n" +
            "sg\n" +
            "gs\n" +
            "sg\n" +
            "gs\n" +
            "sg\n" +
            "\n" +
            "knipbjmtrqoawe\n" +
            "rtaebqkmopjiwn\n" +
            "ewbuqcaijonmrpk\n" +
            "trnmpeqkobjiwa\n" +
            "\n" +
            "puifme\n" +
            "ufb\n" +
            "fvp\n" +
            "rntzlyxwokfcg\n" +
            "\n" +
            "nufjzpyawbqsdgi\n" +
            "ogcmpsdqaxvnzwetklh\n" +
            "\n" +
            "qmdxnfrjobatzwgcyse\n" +
            "rdxtqseawzobygcmfjn\n" +
            "\n" +
            "dbot\n" +
            "dwetlp\n" +
            "odtr\n" +
            "\n" +
            "utbqx\n" +
            "bxuqt\n" +
            "xtbqu\n" +
            "quxbit\n" +
            "\n" +
            "rvthuiqbljzaofgwy\n" +
            "ldftrsjvwoiayzuekcg\n" +
            "dtxmalyuifznvprkcwgoj\n" +
            "\n" +
            "twc\n" +
            "w\n" +
            "pwg\n" +
            "\n" +
            "rmzaoylipcwkvuqesbhn\n" +
            "kpuvhqlwyrabmszecnoi\n" +
            "cwaylknbrhvzmiupseqo\n" +
            "qlwiyczkevsnarhbpumo\n" +
            "\n" +
            "cgr\n" +
            "grch\n" +
            "cgsr\n" +
            "rgce\n" +
            "\n" +
            "eso\n" +
            "ose\n" +
            "soe\n" +
            "\n" +
            "swimuzq\n" +
            "zqwsmliu\n" +
            "iqzurwsmh\n" +
            "iswqzum\n" +
            "wzhumsqi\n" +
            "\n" +
            "amolqcs\n" +
            "sqoayj\n" +
            "sjazqxyo\n" +
            "aqhxsot\n" +
            "ozsajqkx\n" +
            "\n" +
            "qbkyhzfspewgrtlv\n" +
            "pyeqtcbskf\n" +
            "jxbsonqtaykpef\n" +
            "tqskfmyboeup\n" +
            "bdjtfqypokse\n" +
            "\n" +
            "yrtwqacluozbg\n" +
            "vwtfgzmcqobraj\n" +
            "opctryzqawbg\n" +
            "\n" +
            "v\n" +
            "v\n" +
            "v\n" +
            "nv\n" +
            "\n" +
            "dclgejbqrwtkvsxfa\n" +
            "ovgkhjyiqwbmefc\n" +
            "\n" +
            "vpkx\n" +
            "jmydw\n" +
            "fxa\n" +
            "xa\n" +
            "\n" +
            "gwtocmzslfqk\n" +
            "olkgwzcftsmq\n" +
            "ogmsfzlwqckt\n" +
            "\n" +
            "uwxdl\n" +
            "wdux\n" +
            "oxuwdt\n" +
            "dxwu\n" +
            "\n" +
            "ab\n" +
            "smej\n" +
            "t\n" +
            "\n" +
            "iwhlqdermv\n" +
            "menrvqd\n" +
            "jemdqvr\n" +
            "\n" +
            "n\n" +
            "n\n" +
            "a\n" +
            "n\n" +
            "\n" +
            "jqcvetapkbsyu\n" +
            "twndyfrixzhvmsogu\n" +
            "\n" +
            "xsz\n" +
            "zxs\n" +
            "zxs\n" +
            "szx\n" +
            "sxz\n" +
            "\n" +
            "fsatbzpvqjknlrm\n" +
            "pbnljkratfzvsmq\n" +
            "qtrasmjnlkfvbpz\n" +
            "bsjavlmpqktrnzf\n" +
            "qajlbkzvmtsnfrp\n" +
            "\n" +
            "utlchvariswzqjmx\n" +
            "almujswrcthzvfqix\n" +
            "\n" +
            "p\n" +
            "j\n" +
            "p\n" +
            "n\n" +
            "\n" +
            "cgsxwk\n" +
            "uwkcxj\n" +
            "xpwethnkcyb\n" +
            "\n" +
            "gywc\n" +
            "wcgy\n" +
            "ctyugw\n" +
            "gwcy\n" +
            "wgyc\n" +
            "\n" +
            "afmtuw\n" +
            "muatfw\n" +
            "\n" +
            "ujwmnirvkdygtqcabh\n" +
            "takwqdjgzcuivrhnom\n" +
            "cawvrnxfjmghdtkiuq\n" +
            "\n" +
            "srgt\n" +
            "ma\n" +
            "\n" +
            "urnymxabthi\n" +
            "rtxnailuqvoyph\n" +
            "duytknrwiehaxz\n" +
            "rhaumscngtyix\n" +
            "\n" +
            "gawbhtkqruyjel\n" +
            "rlcqbuhawkmyfgjte\n" +
            "jhbyqgkraetwlou\n" +
            "gxbtrnadlejwhyquks\n" +
            "ujfkleagybrtwhq\n" +
            "\n" +
            "dctkngohsxaljfrbvmey\n" +
            "mlbvxaksifyneodgjctrh\n" +
            "lmkfobtyxngsjvrdahec\n" +
            "srkyveohxfmcjdlbtnag\n" +
            "lbguestydkjxfopnvmhcar\n" +
            "\n" +
            "pjrhgzdwcmxq\n" +
            "cgwhmqpjdrxz\n" +
            "\n" +
            "meipjv\n" +
            "mivpje\n" +
            "jevmip\n" +
            "peimjv\n" +
            "vmpeji\n" +
            "\n" +
            "zkcavufyr\n" +
            "fyzuarckv\n" +
            "fvnacqgksry\n" +
            "yvcrfak\n" +
            "crfvyka\n" +
            "\n" +
            "pqynikfxd\n" +
            "dynxqlifpk\n" +
            "\n" +
            "laozucfdek\n" +
            "kpeauocdlz\n" +
            "uoldfsekzac\n" +
            "dmekaclyhnuzo\n" +
            "\n" +
            "hwubponvt\n" +
            "vwytnphobu\n" +
            "vpnbgtwuoh\n" +
            "wpouhvbtn\n" +
            "\n" +
            "wcxlspod\n" +
            "fmedwbtjops\n" +
            "pwnoscid\n" +
            "\n" +
            "ufenjp\n" +
            "ngfxpe\n" +
            "njbpfc\n" +
            "vqnthfazdp\n" +
            "pmfjng\n" +
            "\n" +
            "qrphaykit\n" +
            "qkysrta\n" +
            "jbwdtqrxzav\n" +
            "\n" +
            "wjqfz\n" +
            "jqfaz\n" +
            "\n" +
            "meuxikpsdw\n" +
            "kjimpsdwxu\n" +
            "dmxpwikujs\n" +
            "\n" +
            "fjbsnmcgxz\n" +
            "bpfimjnzduh\n" +
            "\n" +
            "urtkjpo\n" +
            "cthod\n" +
            "\n" +
            "voclmdguaw\n" +
            "oczdlntgmeir\n" +
            "\n" +
            "zipf\n" +
            "fipz\n" +
            "\n" +
            "nbwcexytjzripskmo\n" +
            "kwpzrmtxiosejcb\n" +
            "tsrcoebzpiwjmxk\n" +
            "\n" +
            "jafcwtsukrodynhvqge\n" +
            "pubrlchazvetosyigqjdk\n" +
            "\n" +
            "qminshlycutrdwx\n" +
            "vigzpqbmunacrjftokl\n" +
            "\n" +
            "hweisfpycjdzouvmbnkq\n" +
            "nqjxscbvmuwhzfakdo\n" +
            "\n" +
            "qtndfjcglrkoyux\n" +
            "jqtrlgfkducxnomy\n" +
            "tqnrjxckgfaupdoly\n" +
            "\n" +
            "pbe\n" +
            "b\n" +
            "\n" +
            "n\n" +
            "n\n" +
            "n\n" +
            "n\n" +
            "n\n" +
            "\n" +
            "nsc\n" +
            "ns\n" +
            "nse\n" +
            "\n" +
            "qzkxif\n" +
            "vkfqizx\n" +
            "kfzqix\n" +
            "zixkfq\n" +
            "ifzxkq\n" +
            "\n" +
            "nvshwafe\n" +
            "vbewacnh\n" +
            "nvwmeah\n" +
            "\n" +
            "ziafwxcnmebko\n" +
            "cdfrxmk\n" +
            "fkmpxc\n" +
            "\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "\n" +
            "yauxbwtcvgoq\n" +
            "ywcvotagxbqiu\n" +
            "gqwyvbacouxtn\n" +
            "uobqrcgwtvayx\n" +
            "qcgwoytbxuav\n" +
            "\n" +
            "r\n" +
            "nr\n" +
            "a\n" +
            "r\n" +
            "\n" +
            "xjrkwdnbyuscfgqtphiov\n" +
            "brshqnjcoukxitvywfdpg\n" +
            "vrxlptbcyfdwhgkouqijns\n" +
            "\n" +
            "fqcvwudyiotjblzpxshgnmkrae\n" +
            "ouhrqwtgnjeyxiamfzpdscbkl\n" +
            "\n" +
            "lnch\n" +
            "nhclmg\n" +
            "ldhzcny\n" +
            "\n" +
            "uzfeomrwi\n" +
            "ydgkhjbx\n" +
            "qcylp\n" +
            "\n" +
            "hagpbecorwyvfdz\n" +
            "rstplobhmfnxvykdewc\n" +
            "hfruowdvyjgbpzce\n" +
            "\n" +
            "rgdiznuxa\n" +
            "dragzniue\n" +
            "jzysdgpuvkowqin\n" +
            "lugrndiz\n" +
            "nbdcfugzi\n" +
            "\n" +
            "eqponlctfbwgk\n" +
            "kyjniulbegpdchtwoaq\n" +
            "onczetbplkwqg\n" +
            "\n" +
            "thevzsrc\n" +
            "zcewrsv\n" +
            "vczueosky\n" +
            "wmzlcsve\n" +
            "\n" +
            "sxeqojwkarhyutcdnzp\n" +
            "rjnuwzxpmeysdoctlaq\n" +
            "pzqxeratsdnkuovcwjy\n" +
            "\n" +
            "qexjbo\n" +
            "cqunbaprhwyjfe\n" +
            "ilvegkbszdt\n" +
            "efbmqj\n" +
            "\n" +
            "wm\n" +
            "wm\n" +
            "hm\n" +
            "wm\n" +
            "m\n" +
            "\n" +
            "texosjaiycpqn\n" +
            "mntxspgikeldwycjarq\n" +
            "nysqtaceipjux\n" +
            "phiqznsyxjcvoabet\n" +
            "neqytxcuipsajvf\n" +
            "\n" +
            "z\n" +
            "nozy\n" +
            "\n" +
            "ydfcsvgbikjphamr\n" +
            "wskfdahgpvmrcjby\n" +
            "kpsirchfmjavbdgy\n" +
            "pslxjrugtzydaokemvbcfqh\n" +
            "\n" +
            "t\n" +
            "pyt\n" +
            "\n" +
            "fu\n" +
            "fu\n" +
            "d\n" +
            "yj\n" +
            "fnl\n" +
            "\n" +
            "qxkevrhpna\n" +
            "kmvyorduqe\n" +
            "\n" +
            "sfnmyevqwka\n" +
            "fvmyieawqks\n" +
            "kvfhmctdqjaslywe\n" +
            "ywfkvqeanms\n" +
            "kufwyqmaesvh\n" +
            "\n" +
            "ulvtwepimynb\n" +
            "ehmpnylubtvwi\n" +
            "wplevtunmyib\n" +
            "lpbwnvtuyeim\n" +
            "unvpbgtjiaylmcwes\n" +
            "\n" +
            "zfxkceynsu\n" +
            "xdfzysnuie\n" +
            "efzgxunsy\n" +
            "nzydesxfu\n" +
            "\n" +
            "jneurlkfzxbq\n" +
            "xekznblfurqj\n" +
            "rbzljfkqnxeu\n" +
            "zueknrbxjfylq\n" +
            "xzferlbjqnku\n" +
            "\n" +
            "tr\n" +
            "f\n" +
            "egtr\n" +
            "jmu\n" +
            "s\n" +
            "\n" +
            "aeq\n" +
            "qae\n" +
            "eqa\n" +
            "aeq\n" +
            "\n" +
            "bsgjrilayoezwndvtq\n" +
            "giadlcryjwobhznqesvft\n" +
            "\n" +
            "guxfyzespj\n" +
            "zusejpfgxy\n" +
            "zxygjuefps\n" +
            "\n" +
            "xvmlgpzjdrubqa\n" +
            "jfmbdvzeyrlup\n" +
            "ruzchykmbpwdvloj\n" +
            "vhmuebldrjzpo\n" +
            "bhvcmrypulzjiwds\n" +
            "\n" +
            "cfsjzamyhtoxq\n" +
            "xoysjqfzmhtac\n" +
            "qocxatmfshjzy\n" +
            "\n" +
            "vdhsifmynta\n" +
            "nsmfhdtya\n" +
            "tsnfhamdy\n" +
            "dafyqtsnmh\n" +
            "\n" +
            "rfybkqmh\n" +
            "qoumrd\n" +
            "\n" +
            "l\n" +
            "y\n" +
            "l\n" +
            "y\n" +
            "w\n" +
            "\n" +
            "vlmerz\n" +
            "mlvrze\n" +
            "zvrmle\n" +
            "zelrvm\n" +
            "mzlrve\n" +
            "\n" +
            "rnb\n" +
            "gdcb\n" +
            "\n" +
            "pbtergc\n" +
            "tecfjgr\n" +
            "\n" +
            "ogzsajwvdiplrtxbhfcnky\n" +
            "btjzlswhikyofgcpvrnda\n" +
            "tbwinagrhfyscvlejkdop\n" +
            "dakhrbipqglmovjyncswtf\n" +
            "bhyljrdpsktgfiancwov\n" +
            "\n" +
            "qolmnyvhtwe\n" +
            "uwkecxshldmoy\n" +
            "zwblsockyumh\n" +
            "miywfgjhaopr\n" +
            "\n" +
            "u\n" +
            "u\n" +
            "q\n" +
            "\n" +
            "zdxynqmev\n" +
            "bdexmzyiqcn\n" +
            "\n" +
            "bwtqagf\n" +
            "tnmwfaqbj\n" +
            "\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "\n" +
            "yjgicnxerbsu\n" +
            "xpzfqirsjh\n" +
            "exswmarikbj\n" +
            "mjxgrsi\n" +
            "\n" +
            "tvzkbxugmcnshproiw\n" +
            "czxtirownbmpksuvgh\n" +
            "cnofirbgmhzuspvtxwk\n" +
            "gmctsrohkxwzupvbni\n" +
            "vsgbzcmktxihonwupr\n" +
            "\n" +
            "dyaoim\n" +
            "aiom\n" +
            "ozimual\n" +
            "oxaim\n" +
            "biyotma\n" +
            "\n" +
            "saliju\n" +
            "evzhxcobk\n" +
            "lj\n" +
            "\n" +
            "txhebw\n" +
            "etwhbx\n" +
            "uhwxtbe\n" +
            "\n" +
            "eyaixfrdhoqksc\n" +
            "eakiqsrocxyhd\n" +
            "\n" +
            "vkr\n" +
            "kvr\n" +
            "kvr\n" +
            "\n" +
            "surjoh\n" +
            "ubh\n" +
            "ubmahe\n" +
            "uh\n" +
            "\n" +
            "vhkcawrno\n" +
            "vowahrnkc\n" +
            "oknarvwhc\n" +
            "cnkhvwoar\n" +
            "wvhkanrco\n" +
            "\n" +
            "ntpfemsvialxgrwqzc\n" +
            "kcwegrtispxnyd\n" +
            "phstgwixebnucr\n" +
            "xpwjtenscoigr\n" +
            "\n" +
            "sfanq\n" +
            "xgtzfrn\n" +
            "ulfinpkv\n" +
            "\n" +
            "kdwnyjuzctiqpgf\n" +
            "ngtcrjipqfyh\n" +
            "ypfvcqntirgjh\n" +
            "\n" +
            "urmtsh\n" +
            "svihtu\n" +
            "utmph\n" +
            "juthydwafcqx\n" +
            "uthve\n" +
            "\n" +
            "sk\n" +
            "ks\n" +
            "sk\n" +
            "\n" +
            "zxbvcrgyqfjtoeiudwpkhsm\n" +
            "igkswrpohqudcfjxzmvytb\n" +
            "cpatkzfuoyqgvrsmibhxjdw\n" +
            "\n" +
            "kvgumiabnoh\n" +
            "bvaiomgnukhc\n" +
            "mkhnvusbagio\n" +
            "hamiobunkgv\n" +
            "umsgovkahbin\n" +
            "\n" +
            "yrceuq\n" +
            "rmdbpa\n" +
            "nkvxjslwg\n" +
            "\n" +
            "lkt\n" +
            "fl\n" +
            "vil\n" +
            "\n" +
            "whn\n" +
            "hn\n" +
            "hn\n" +
            "\n" +
            "gvebcszypdlkqm\n" +
            "zcyhdlpqgsvke\n" +
            "cdzbylqkpsuveg\n" +
            "pzsyxlgdaiofcqwvek\n" +
            "gmcpvyqzeskld\n" +
            "\n" +
            "ryzfspdtbwxiomhkjnlu\n" +
            "tqihvployrmksbunzfwc\n" +
            "\n" +
            "dualjxigyrzb\n" +
            "durysxjlgzaib\n" +
            "srgxulazbjyid\n" +
            "lrgaubjydzxi\n" +
            "azritbxdpljyg\n" +
            "\n" +
            "cfahxspjelitdnobuvqywk\n" +
            "vwmkoxulnypfiatgjbhrcsq\n" +
            "\n" +
            "f\n" +
            "f\n" +
            "f\n" +
            "f\n" +
            "f\n" +
            "\n" +
            "grbmahpise\n" +
            "mbireyxhalgs\n" +
            "\n" +
            "bcrkvuwqt\n" +
            "trubckq\n" +
            "rbuqtkc\n" +
            "trkbcuq\n" +
            "rubtqkc\n" +
            "\n" +
            "zxpbejmvhrutwlkq\n" +
            "gtvrzphoqcbnmju\n" +
            "pjazbvqurgmysht\n" +
            "fhsptiumrvjqbz\n" +
            "\n" +
            "kpszjieflb\n" +
            "blsijkefzp\n" +
            "zksjiefpbgl\n" +
            "ilbzrksajpfe\n" +
            "sglzbepfjik\n" +
            "\n" +
            "nxwohsipd\n" +
            "zitjrlvfgsoym\n" +
            "bqsiopuc\n" +
            "aoisd\n" +
            "\n" +
            "wj\n" +
            "j\n" +
            "fzpglynjeu\n" +
            "jk\n" +
            "ikj\n" +
            "\n" +
            "abzftcqvgsrnexpmho\n" +
            "pxvlybndrtqimzhosacgef\n" +
            "nocqfzerjaubxthgmwspv\n" +
            "\n" +
            "psauzryot\n" +
            "vmdhbwe\n" +
            "lfc\n" +
            "gsri\n" +
            "sqya\n" +
            "\n" +
            "lkjudnqterhyscgx\n" +
            "eckqhlxybrngudstj\n" +
            "wotecvlyrpgqmijxkhsd\n" +
            "\n" +
            "htpc\n" +
            "caph\n" +
            "hpustjc\n" +
            "nyhcedmgp\n" +
            "\n" +
            "ezaljkfpiyvroud\n" +
            "hbiwxfstmldkecnvpgqo\n" +
            "\n" +
            "kiqvzyjrthmblu\n" +
            "ahszlduemxcij\n" +
            "\n" +
            "wirunkh\n" +
            "hwqdknyirul\n" +
            "kxwuhirn\n" +
            "hkirwnu\n" +
            "ierwunkh\n" +
            "\n" +
            "vcgno\n" +
            "snmicvo\n" +
            "ncomjisv\n" +
            "coynuv\n" +
            "lconfdvpz\n" +
            "\n" +
            "tgqkhowsyfbzpcur\n" +
            "zcqsugtwhrpfy\n" +
            "fgydqpcjswrlzeuth\n" +
            "thgpcfyzqeursw\n" +
            "\n" +
            "rwpci\n" +
            "cipwr\n" +
            "\n" +
            "ptrlaqebo\n" +
            "pebtlaqor\n" +
            "qboxepatr\n" +
            "epbartoq\n" +
            "\n" +
            "fypd\n" +
            "dpyf\n" +
            "ypfd\n" +
            "fdpy\n" +
            "\n" +
            "c\n" +
            "c\n" +
            "c\n" +
            "d\n" +
            "c\n" +
            "\n" +
            "gxysqiamkpc\n" +
            "mpiacyqxkgs\n" +
            "\n" +
            "mvqbskuzefy\n" +
            "zcsqebma\n" +
            "ztbnlhe\n" +
            "\n" +
            "snx\n" +
            "xsn\n" +
            "nkxs\n" +
            "snx\n" +
            "\n" +
            "joyblxztkswmvnec\n" +
            "gdcrhykmfseqapibzu\n" +
            "\n" +
            "oqzmprikt\n" +
            "fhlgxucda\n" +
            "\n" +
            "ygrjkfazu\n" +
            "kjiagrzyfu\n" +
            "\n" +
            "btg\n" +
            "o\n" +
            "v\n" +
            "oc\n" +
            "\n" +
            "bnqyz\n" +
            "ebdfls\n" +
            "\n" +
            "vjhocqkamygbplu\n" +
            "dbwsyefuxzntijrc\n" +
            "\n" +
            "kmlb\n" +
            "kqsbl\n" +
            "\n" +
            "vhjsdxrfpokyznibwgtmu\n" +
            "syvkmzfjgpdwixrnbutoh\n" +
            "uzbjgvhdkpynmtfoxsrlwi\n" +
            "jpkxwvyrgftzioubhsmnd\n" +
            "ykjmzvsqnhxwgbrutoipdf\n" +
            "\n" +
            "hwby\n" +
            "yvbmhl\n" +
            "echgiyabjpf\n" +
            "krbouyh\n" +
            "hrynotb\n" +
            "\n" +
            "tobipzwfxy\n" +
            "pfxwytizob\n" +
            "hsfwzpbotiyax\n" +
            "\n" +
            "znrgilpcfse\n" +
            "seinczlpgrf\n" +
            "nircgepszfl\n" +
            "rcegzsiflpn\n" +
            "lzgrcpensfi\n" +
            "\n" +
            "tupvbxcgfnmh\n" +
            "fpqntvibgxhmc\n" +
            "npbtvxghfm\n" +
            "tvxfhmbnipg\n" +
            "rnvxmhfjgpbt\n" +
            "\n" +
            "inysghdka\n" +
            "wbc\n" +
            "\n" +
            "noktsjqvmzxheplrcfgiuwda\n" +
            "dlogmasfzwhupjrkcntixqev\n" +
            "\n" +
            "zhwfbs\n" +
            "bzcwh\n" +
            "\n" +
            "igqkpctmafr\n" +
            "jietalnfksqp\n" +
            "\n" +
            "ewlanjvgdbpm\n" +
            "lpjangwvem\n" +
            "vpngjwmeal\n" +
            "glvwnpejam\n" +
            "enlgwjmvpa\n" +
            "\n" +
            "niocufzwrk\n" +
            "kirmuzfocvw\n" +
            "\n" +
            "juqervaxni\n" +
            "cudjqavnix\n" +
            "iuvjndcaxq\n" +
            "xvniqajugd\n" +
            "vxunjiaq\n" +
            "\n" +
            "lmayozkep\n" +
            "koazylep\n" +
            "aeykzlop\n" +
            "\n" +
            "ejgotzhrxbsnqimu\n" +
            "lrspkgobcaywmjfvhd\n" +
            "\n" +
            "uazxfrony\n" +
            "uoaxynzrf\n" +
            "yunaorxfz\n" +
            "\n" +
            "lowmgiuxpnakzsq\n" +
            "qwaomukglnx\n" +
            "ubgkoyqanwlvmx\n" +
            "lowaqgyxunkhm\n" +
            "\n" +
            "alfoj\n" +
            "floj\n" +
            "\n" +
            "yglkurfahidmoxtvz\n" +
            "muykfdrzivlothga\n" +
            "devylsarcupgoihkmftz\n" +
            "rmtgkalydnhvozubfi\n" +
            "ahrzqodkgxyuitvmfl\n" +
            "\n" +
            "gmdoshlaixnc\n" +
            "xhmicdgosanl\n" +
            "hiqgvbulakdmoxcpn\n" +
            "hoiamdsngcxtl\n" +
            "\n" +
            "egnprq\n" +
            "ash\n" +
            "\n" +
            "oabx\n" +
            "abxfo\n" +
            "\n" +
            "vomitazdbflqhkue\n" +
            "lvemipubdafohztkq\n" +
            "dkabtiylqgzuovehmf\n" +
            "\n" +
            "euanfbq\n" +
            "skufxtami\n" +
            "nefauc\n" +
            "\n" +
            "fadpbjxvzeghqkriy\n" +
            "xpaqfzjvybdhrkieg\n" +
            "jeqghzxrdyvakpfbwi\n" +
            "ygvakzbdpqrxjfeiht\n" +
            "\n" +
            "dhvmgjoqzknbwyl\n" +
            "hvnlobmydwzqkjg\n" +
            "vbzljhdqgnmwoyk\n" +
            "\n" +
            "s\n" +
            "k\n" +
            "sk\n" +
            "d\n" +
            "\n" +
            "svzubcigpeqdthfmxnj\n" +
            "djogszbcnvefqthiuxmp\n" +
            "\n" +
            "vgkpjwymduqfxcztoasne\n" +
            "swgapuymcvqnjodtkfzxe\n" +
            "\n" +
            "stgv\n" +
            "yvbts\n" +
            "iokqv\n" +
            "\n" +
            "h\n" +
            "h\n" +
            "h\n" +
            "ujxw\n" +
            "\n" +
            "uz\n" +
            "uz\n" +
            "uz\n" +
            "\n" +
            "cdh\n" +
            "lhg\n" +
            "mkh\n" +
            "quroafxhipsev\n" +
            "\n" +
            "d\n" +
            "d\n" +
            "dg\n" +
            "\n" +
            "lbrsefwhxagdmpqjiocuvyn\n" +
            "uobfgnhvsqwzlkjyraicdpm\n" +
            "\n" +
            "uwnvthio\n" +
            "\n" +
            "yudxpkhrngb\n" +
            "selctamwozqvf\n" +
            "\n" +
            "ueiypcnoa\n" +
            "nidaehvt\n" +
            "akencir\n" +
            "\n" +
            "ozcru\n" +
            "uoflar\n" +
            "pwoxuyvm\n" +
            "\n" +
            "nrgaujbldiwxvq\n" +
            "sdvuirgaynbj\n" +
            "\n" +
            "synqkzdlpebticorvwxmaug\n" +
            "ekyatuvbpohmxnfdgczirwql\n" +
            "ztvwupairdeqmckgbnylxo\n" +
            "alngerwtckpvmioxbduzyq\n" +
            "\n" +
            "dqygzrkuowejsm\n" +
            "zyikwtjsver\n" +
            "yzjrsvawceik\n" +
            "\n" +
            "lqduw\n" +
            "iudw\n" +
            "wdrue\n" +
            "\n" +
            "zxnrflac\n" +
            "lx\n" +
            "lvx\n" +
            "otlwkx\n" +
            "wxyl\n" +
            "\n" +
            "q\n" +
            "q\n" +
            "q\n" +
            "q\n" +
            "q\n" +
            "\n" +
            "aigmyqxscvhde\n" +
            "csegmkqdnvyahix\n" +
            "gvqixcdheysam\n" +
            "dsmyaexgivqhc\n" +
            "shiqmxgdeycva\n" +
            "\n" +
            "nbmovulhpai\n" +
            "yfcobuiaetpdvmln\n" +
            "mnopuvlbia\n" +
            "wviopnmluabk\n" +
            "uvamohipklnb\n" +
            "\n" +
            "cibznrjtsgoafdlkx\n" +
            "cethszlarinx\n" +
            "xcsztairehnlp\n" +
            "szhnatlxicr\n" +
            "mpselnxatyzric\n" +
            "\n" +
            "qxdzauyvbc\n" +
            "qxzvabdcuy\n" +
            "zyxabucqsdv\n" +
            "\n" +
            "uzxvatmprofyjcliwgbdsqnek\n" +
            "kynesjvmoifucbpqwxlzrdtga\n" +
            "\n" +
            "mepouwaj\n" +
            "cutjoxvpa\n" +
            "apojcvftd\n" +
            "opwdaj\n" +
            "njhzgqrikyapslo\n" +
            "\n" +
            "efqisyl\n" +
            "elfqsiy\n" +
            "sfiqley\n" +
            "\n" +
            "if\n" +
            "wvzghe\n" +
            "xn\n" +
            "dnxu\n" +
            "\n" +
            "afuolgsxdckypbenqjhmr\n" +
            "euqojgbfzphxmnrysda\n" +
            "xsbwrdmnfqyphaegjuo\n" +
            "xsfuhpgnbjmwqoaeryd\n" +
            "\n" +
            "xjyizvdsbkfmhenwop\n" +
            "mueiojtyqnag\n" +
            "\n" +
            "bjlvkzugwqspcihmxr\n" +
            "mlugrxwjqsvibczhkp\n" +
            "vikuscpzwqhmgjxrbl\n" +
            "pxzbksqmjlcgihurvw\n" +
            "\n" +
            "payfmlnhgtzsrxke\n" +
            "yeknlfshmrgztx\n" +
            "\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "p\n" +
            "\n" +
            "gnmcwdtquesz\n" +
            "ztdscnkg\n" +
            "zdancosjgt\n" +
            "cdntzsg\n" +
            "zcjgbpstrnd\n" +
            "\n" +
            "ugxawjehznr\n" +
            "gujxqzrwhnea\n" +
            "rewagunjzhx\n" +
            "\n" +
            "krvmqtuiwsezbjcdhployaxngf\n" +
            "xkwsubhjlfvparcgomyenidzqt\n" +
            "\n" +
            "jrglbkzcwtuayno\n" +
            "iwydqmzt\n" +
            "tdwfeyz\n" +
            "\n" +
            "jnvchaxzotqd\n" +
            "jdaohpexnt\n" +
            "\n" +
            "yifrdlua\n" +
            "asridu\n" +
            "\n" +
            "rchuily\n" +
            "brliyc\n" +
            "icyl\n" +
            "nclfjxiytvs\n" +
            "hiycrl\n" +
            "\n" +
            "fj\n" +
            "fj\n" +
            "jf\n" +
            "jf\n" +
            "\n" +
            "hncwvidj\n" +
            "ncijh\n" +
            "qjhrin\n" +
            "zsxiheynj\n" +
            "jvihaqnc\n" +
            "\n" +
            "zkraj\n" +
            "zkjrl\n" +
            "akjzr\n" +
            "zsvjrk\n" +
            "\n" +
            "culpozwn\n" +
            "copkslvruwt\n" +
            "fhwlecupo\n" +
            "\n" +
            "cuibdzoagynvrkw\n" +
            "dobjkzuxvrcyinag\n" +
            "ipsduzkvybnoacrmeqg\n" +
            "\n" +
            "gjwfeblzasoirpvhcqtxu\n" +
            "dcfqurpiaxslgjhbyzwmeno\n" +
            "\n" +
            "agi\n" +
            "sa\n" +
            "vuhaksj\n" +
            "zatyex\n" +
            "\n" +
            "xponks\n" +
            "ojnkpsx\n" +
            "\n" +
            "cqeiyuforpx\n" +
            "bxfnzrs\n" +
            "xhfnvdr\n" +
            "rfx\n" +
            "\n" +
            "tqowdj\n" +
            "dw\n" +
            "diwfu\n" +
            "dfewgi\n" +
            "wd\n" +
            "\n" +
            "dyvjwabnuzgx\n" +
            "bjdyglxvzonw\n" +
            "dxbwnyvagjz\n" +
            "zyiwdcgrbjexvn\n" +
            "xjngvztwbdy\n" +
            "\n" +
            "ob\n" +
            "ob\n" +
            "bo\n" +
            "ob\n" +
            "\n" +
            "cp\n" +
            "cp\n" +
            "cg\n" +
            "\n" +
            "cnwlshdkyboxmpvtz\n" +
            "ndswvmyzjeuprbgchl\n" +
            "ayzkbswhlnfptcvdqm\n" +
            "\n" +
            "cmfyketonuixwdgpav\n" +
            "xeyngtvuwfcdik\n" +
            "xdufiwcnekvtgy\n" +
            "zuvyixgbsdhwnjkelcf\n" +
            "xwdfvucyinekgr\n" +
            "\n" +
            "vwznkidlhxuaosfr\n" +
            "rhakozvwgfisdunl\n" +
            "korahvzwdsyilnuf\n" +
            "fhniwvurokxszald\n" +
            "\n" +
            "rlhewm\n" +
            "whpr\n" +
            "wraqfh\n" +
            "\n" +
            "szpvechrdnybfjmog\n" +
            "vgptfyjmbdcxzshe\n" +
            "zhsfqepvtygnbjmdc\n" +
            "yzhjalgcusdpfbmveik\n" +
            "\n" +
            "xapwbucizkl\n" +
            "qgs\n" +
            "yoehs\n" +
            "jrsge\n" +
            "vjgdtm\n" +
            "\n" +
            "vxyuftcbpl\n" +
            "uycftxlbpv\n" +
            "vtxflpbycu\n" +
            "pbcxfvtlyu\n" +
            "xylavcftupb\n" +
            "\n" +
            "yhbadxqs\n" +
            "hqdxsay\n" +
            "zphxtaqsd\n" +
            "asdoeqxhfnj\n" +
            "\n" +
            "tlmrid\n" +
            "osmrjwlvge\n" +
            "\n" +
            "hfprkgzljcs\n" +
            "slghpczfjrk\n" +
            "flcjzshpgrk\n" +
            "hzfcjsgklpr\n" +
            "rgphlfjkzcs\n" +
            "\n" +
            "jizfvmyocxq\n" +
            "kogmzyjiqv\n" +
            "ujnqwpaszvhymro\n" +
            "gxomvzjcqy\n" +
            "\n" +
            "ie\n" +
            "ie\n" +
            "piec\n" +
            "ei\n" +
            "\n" +
            "tvaxzm\n" +
            "txamv\n" +
            "\n" +
            "puqcatmbe\n" +
            "bcuqto\n" +
            "ubsiqhzgc\n" +
            "\n" +
            "vkqogu\n" +
            "oqfhigvudm\n" +
            "voqubg\n" +
            "\n" +
            "zlfapsjxtm\n" +
            "umalzjpfosxt\n" +
            "jplsftaxzm\n" +
            "tafzxlpqsbjm\n" +
            "\n" +
            "zicyojr\n" +
            "ilzcyr\n" +
            "hzcrtleyvipf\n" +
            "zicypr\n" +
            "yicezur\n" +
            "\n" +
            "ehigkrowmvjylnxb\n" +
            "tihkwoxbjelnmrvy\n" +
            "nkjbmxwhoelrviy\n" +
            "vnojlkwxrmhbeiy\n" +
            "lvkhxnowmjeyrib\n" +
            "\n" +
            "bpzgcrtoisywvned\n" +
            "acdwbrytesguv\n" +
            "\n" +
            "b\n" +
            "qb\n" +
            "ba\n" +
            "bh\n" +
            "b\n" +
            "\n" +
            "hntmvbilk\n" +
            "tnmbzvl\n" +
            "vbfnmt\n" +
            "yvnomuxbtw\n" +
            "\n" +
            "ib\n" +
            "ib\n" +
            "lib\n" +
            "\n" +
            "jefqbsd\n" +
            "iyhzrvcngl\n" +
            "\n" +
            "zaeqfuhynlbxipwvgotkd\n" +
            "kagozfcnbirmpuesywdv\n" +
            "\n" +
            "wfulhibnvtapkyrq\n" +
            "ibleqfykavprunmxwth\n" +
            "raulpqfwbhvintyk\n" +
            "vnwrklhufytbapiq\n" +
            "bknqpvrytfuhlwai\n" +
            "\n" +
            "wtgqajfmk\n" +
            "mwbfcjukqga\n" +
            "fmghkjwaq\n" +
            "gfawqmjk\n" +
            "fjwmkgaq\n" +
            "\n" +
            "lxk\n" +
            "t\n" +
            "w\n" +
            "w\n" +
            "mf\n" +
            "\n" +
            "mnzbcw\n" +
            "rad\n" +
            "ejpxykvhu\n" +
            "zslo\n" +
            "\n" +
            "fatkelbspwjyhoqrdui\n" +
            "qsngucrzamvx\n" +
            "\n" +
            "ldwhapn\n" +
            "wnma\n" +
            "awn\n" +
            "wnau\n" +
            "naw\n" +
            "\n" +
            "fnrgykvulp\n" +
            "vyrlupngk\n" +
            "kynprgualvq\n" +
            "\n" +
            "oz\n" +
            "oz\n" +
            "oz\n" +
            "zo\n" +
            "\n" +
            "dehqmlkfyxpvujagbtcwio\n" +
            "huapickwemyblxodftjvgq\n" +
            "pagblyvnjotwekuhcfxiqm\n" +
            "qjythibopgxaeckmwvluf\n" +
            "\n" +
            "huclkitbnrad\n" +
            "uhdoictnrklba\n" +
            "tlcbauhdinrk\n" +
            "\n" +
            "pamdyrxtj\n" +
            "pktnmarybxjd\n" +
            "\n" +
            "tr\n" +
            "drt\n" +
            "rkt\n" +
            "tor\n" +
            "rt\n" +
            "\n" +
            "gjrclwxyuk\n" +
            "isqmdbf\n" +
            "eoivmdfpt\n" +
            "\n" +
            "qvg\n" +
            "i\n" +
            "ui\n" +
            "\n" +
            "j\n" +
            "l\n" +
            "u\n" +
            "lu\n" +
            "osd\n" +
            "\n" +
            "zmdknlf\n" +
            "nzlfmdk\n" +
            "dmznfkl\n" +
            "dzlnkfm\n" +
            "\n" +
            "ozdievpxm\n" +
            "mzoxdiepv\n" +
            "idpzexovm\n" +
            "ovdemzxpi\n" +
            "\n" +
            "cbyrndpwk\n" +
            "kozyrncdp\n" +
            "ujcksndxphyf\n" +
            "dnbpkyc\n" +
            "\n" +
            "e\n" +
            "e\n" +
            "e\n" +
            "w\n" +
            "\n" +
            "tpndq\n" +
            "igpajc\n" +
            "\n" +
            "gihvnzfacujpoelxqkr\n" +
            "mqfjnrodzkuvxaipel\n" +
            "okwanixqlpjufevr\n" +
            "rxipfjtasnekyulqvob\n" +
            "\n" +
            "jmgeixvhaoknq\n" +
            "qloihgekvjxman\n" +
            "ajoghikvmpxnqe\n" +
            "ingovjkaehqmx\n" +
            "\n" +
            "szualfd\n" +
            "zsulfaw\n" +
            "\n" +
            "osajgkmyfvri\n" +
            "hwmisgbaqf\n" +
            "\n" +
            "bvzm\n" +
            "izwrn\n" +
            "zsfd\n" +
            "mz\n" +
            "\n" +
            "kixhabnoqpzsg\n" +
            "gpnxaikqobzsh\n" +
            "argcboiqznkxsph\n" +
            "oaqgicsndhkbzxp\n" +
            "jzxhpstoinqbkga\n" +
            "\n" +
            "fkisv\n" +
            "fvisdrk\n" +
            "vkmisf\n" +
            "ksifqv\n" +
            "ifspvk\n" +
            "\n" +
            "ovwqbshjirpg\n" +
            "iohbgfjqcrvt\n" +
            "\n" +
            "efsqtnoywmkzrv\n" +
            "gwsotczmkdyqlrve\n" +
            "zmverktswfynqo\n" +
            "\n" +
            "rwtuihvjqofszxaykn\n" +
            "riqntxydpcakjbgo\n" +
            "\n" +
            "mzkndrhabvj\n" +
            "gywofampnlxbhsi\n" +
            "hbtenma\n" +
            "rcamubhn\n" +
            "bmndhkja\n" +
            "\n" +
            "afsnkue\n" +
            "pfcvirzydqbetlk\n" +
            "\n" +
            "zftwoivcr\n" +
            "rtvzwix\n" +
            "kzjwtrgi\n" +
            "hitwzor\n" +
            "\n" +
            "harkxeinjtgpy\n" +
            "tprbwighzeksymcv\n" +
            "\n" +
            "qecrsugzdho\n" +
            "uwdxocqyftnbzhl\n" +
            "dcrzqhuso\n" +
            "sdchqozu\n" +
            "\n" +
            "cu\n" +
            "u\n" +
            "u\n" +
            "u\n" +
            "\n" +
            "whlfczpqa\n" +
            "yfzhpqc\n" +
            "zpfobxkhqc\n" +
            "cfzhqp\n" +
            "fcozqhp\n" +
            "\n" +
            "erbnkjqouhg\n" +
            "qsthnrjiwxvzkaf\n" +
            "yncqejdukrh\n" +
            "klqubphrnj\n" +
            "\n" +
            "ikvyfmlpacez\n" +
            "mzeiplkacvfy\n" +
            "lyfzipvcmeqak\n" +
            "\n" +
            "qo\n" +
            "h\n" +
            "\n" +
            "neuzqjk\n" +
            "ixqhknj\n" +
            "pvbrygdacs\n" +
            "\n" +
            "xf\n" +
            "ef\n" +
            "f\n" +
            "f\n" +
            "\n" +
            "t\n" +
            "t\n" +
            "\n" +
            "j\n" +
            "z\n" +
            "ybx\n" +
            "a\n" +
            "\n" +
            "ewbmvucapsxkig\n" +
            "ksiprxbvagwfme\n" +
            "agdmiwexvsbpk\n" +
            "egisawxkpmbv\n" +
            "\n" +
            "dykmbtv\n" +
            "dtjkmyv\n" +
            "mvkdtyc\n" +
            "ydkmtv\n" +
            "\n" +
            "zw\n" +
            "o\n" +
            "i\n" +
            "oi\n" +
            "r\n" +
            "\n" +
            "hjybnqczotxgeiaup\n" +
            "cpygejxuzhonitqab\n" +
            "jnauyiohtcepqbzgx\n" +
            "uaqtnyicgezoxjpbh\n" +
            "nptbcijxzuoeayqgh\n" +
            "\n" +
            "owynpg\n" +
            "wpyn\n" +
            "pnwy\n" +
            "ywpn\n" +
            "\n" +
            "fqoishlxzarmkc\n" +
            "dstzjmxrvfckuoi\n" +
            "xsmozrfcik\n" +
            "zmgsrcwiofxpku\n" +
            "igrkebsfoxcmdz\n" +
            "\n" +
            "moas\n" +
            "xdcfmoa\n" +
            "\n" +
            "xltpwzrf\n" +
            "erbhflxwzntp\n" +
            "tnsrbxlawpzf\n" +
            "rtzwuoxipfl\n" +
            "\n" +
            "yesonitqag\n" +
            "etigoaqmynshc\n" +
            "tpneigasoqy\n" +
            "\n" +
            "pnmvfgwyierqukct\n" +
            "tcnuigmqpeyrwvk\n" +
            "\n" +
            "qza\n" +
            "zaqr\n" +
            "zqa\n" +
            "qza\n" +
            "qza\n" +
            "\n" +
            "dyphutng\n" +
            "ghntydup\n" +
            "thpudywng\n" +
            "tpudyhgn\n" +
            "\n" +
            "gofac\n" +
            "homgpwae\n" +
            "govmnaw\n" +
            "azsgo\n" +
            "apgmyuo\n" +
            "\n" +
            "bsvqmnidyogzuewtk\n" +
            "qitsokmnewdbuy\n" +
            "iqskwxyonmuetdb\n" +
            "kbmsundoywiqte\n" +
            "\n" +
            "uoqj\n" +
            "jvs\n" +
            "yjazt\n" +
            "j\n" +
            "\n" +
            "r\n" +
            "o\n" +
            "nv\n" +
            "oy\n" +
            "r\n" +
            "\n" +
            "u\n" +
            "ru\n" +
            "\n" +
            "avofjnwdehrpyklqugzimtx\n" +
            "gfjlwkrahzqvneodmutpyxi\n" +
            "mgpjlfuxoyvzwqtdhaeknir\n" +
            "ryfqedjgpnikawmtxhvuloz\n" +
            "gidrokyntxavfwpmqelhzujc\n" +
            "\n" +
            "k\n" +
            "mzp\n" +
            "\n" +
            "jfpow\n" +
            "jfop\n" +
            "pfjo\n" +
            "\n" +
            "qokte\n" +
            "eno\n" +
            "woef\n" +
            "\n" +
            "qnart\n" +
            "utaqr\n" +
            "\n" +
            "ajqivchfpem\n" +
            "upvqhcjmafe\n" +
            "pvewjfhmcqa\n" +
            "vmjpecaqhf\n" +
            "cahpfemjvq\n" +
            "\n" +
            "ayw\n" +
            "kp\n" +
            "\n" +
            "rixwjogsfhuyvebnp\n" +
            "vexwuhjyogrfisnbp\n" +
            "psyfwhrxeogjubnvi\n" +
            "yjvswhnrogixbufpe\n" +
            "\n" +
            "eylbtgqvronjfzphw\n" +
            "brhqvoptnjeygwflz\n" +
            "rwhlpzbgjvoneyqtf\n" +
            "hcvlnbegyrfwtpozjq\n" +
            "ynwefqphlvrotbjzg\n" +
            "\n" +
            "xyu\n" +
            "xy\n" +
            "\n" +
            "bj\n" +
            "j\n" +
            "j\n" +
            "j\n" +
            "\n" +
            "kocgiwr\n" +
            "ibksgowc\n" +
            "ijkcwog\n" +
            "wiegjcaok\n" +
            "\n" +
            "rlt\n" +
            "ltr\n" +
            "lrt\n" +
            "rlt\n" +
            "lrt\n" +
            "\n" +
            "xjoc\n" +
            "jcoxz\n" +
            "cxjo\n" +
            "\n" +
            "r\n" +
            "r\n" +
            "amrtqgfw\n" +
            "udr\n" +
            "sderl\n" +
            "\n" +
            "vonauts\n" +
            "atxsyvco\n" +
            "psroawlevbjdgk\n" +
            "smvzhqoya\n" +
            "\n" +
            "ubwotjecsqhadvkf\n" +
            "ufqkjtesadhvcbow\n" +
            "\n" +
            "pbqsuatrzk\n" +
            "rsquzpobk\n" +
            "pqsrbzkdu\n" +
            "zqcusrkpvb\n" +
            "spbkqrzu\n" +
            "\n" +
            "vqwcinpb\n" +
            "aiejfduvpht\n" +
            "zowvpinrxqml\n" +
            "\n" +
            "zufk\n" +
            "kwe\n" +
            "k\n" +
            "mk\n" +
            "wko\n" +
            "\n" +
            "lydtzkhwajf\n" +
            "xrphuebsogm\n" +
            "nsucmhgqpx\n" +
            "\n" +
            "mwhlnfotz\n" +
            "shvfwmanl\n" +
            "\n" +
            "xfywodzc\n" +
            "fyoxchw\n" +
            "howycfx\n" +
            "owyhfxc\n" +
            "xwocyf\n" +
            "\n" +
            "hri\n" +
            "rv\n" +
            "lzr\n" +
            "r\n" +
            "nrfc\n" +
            "\n" +
            "mkd\n" +
            "yvjkoguaxip\n" +
            "nwkz\n" +
            "bcktdsmqf\n" +
            "sznkw\n" +
            "\n" +
            "flhbygto\n" +
            "ftbylhoa\n" +
            "otbyflh\n" +
            "yhbtfol\n" +
            "\n" +
            "rnphowmiy\n" +
            "hpwrmoyis\n" +
            "iunworypmh\n" +
            "diyrwhnmpo\n" +
            "\n" +
            "qlhfdcg\n" +
            "plju\n" +
            "rl\n" +
            "nalk\n" +
            "lep\n" +
            "\n" +
            "xwcropjbzkdegnufsqiht\n" +
            "rcidlowgxnsktqpbheyzfju\n" +
            "ctfxzgvprnhbqeodkwjisu\n" +
            "\n" +
            "wgzu\n" +
            "fkbuxrwg\n" +
            "gwjyuhzn\n" +
            "nhjyzuwg\n" +
            "\n" +
            "rwbm\n" +
            "wmkrs\n" +
            "\n" +
            "itzekynp\n" +
            "dkepiunyt\n" +
            "vmwlbgkcipnseqr\n" +
            "\n" +
            "xlkbgo\n" +
            "kgz\n" +
            "kag\n" +
            "\n" +
            "i\n" +
            "x\n" +
            "htq\n" +
            "sot\n" +
            "f\n" +
            "\n" +
            "kuqperwixsgvbctyjfdn\n" +
            "qjcdstpxvyuwifnbre\n" +
            "atqumpwrefdxvoijcznys\n" +
            "rfxdcuispnewjtkyqv\n" +
            "\n" +
            "imdwuntbahxvj\n" +
            "daniwhemzxtjb\n" +
            "nhmajglidtxvwb\n" +
            "tbjinhxwymad\n" +
            "csaqnhdtfrmjobwkix\n" +
            "\n" +
            "esjkcgpf\n" +
            "gmfszpk\n" +
            "pfgksj\n" +
            "\n" +
            "i\n" +
            "i\n" +
            "i\n" +
            "i\n" +
            "\n" +
            "alnj\n" +
            "zucmhenrtoq\n" +
            "bkn\n" +
            "nifp\n" +
            "nvi\n" +
            "\n" +
            "mjkagdfsilctvpwhuq\n" +
            "wufhtjlgpaivcqdsmk\n" +
            "qutsghdvkmcwfaijlp\n" +
            "vutlpwschfkamqjdgi\n" +
            "isjwtmqkvfgalupcdh\n" +
            "\n" +
            "ynsgxmfoelkd\n" +
            "yxmvgkd\n" +
            "vgmykxd\n" +
            "gmyhkdx\n" +
            "ygxmkdz\n" +
            "\n" +
            "vldyroebks\n" +
            "osverdjlyb\n" +
            "eszyrudvblo\n" +
            "rvdqomlcbtygse\n" +
            "oredlbvsy\n" +
            "\n" +
            "o\n" +
            "o\n" +
            "o\n" +
            "o\n" +
            "jvmo\n" +
            "\n" +
            "jbkpwnc\n" +
            "dtwrpiqbsf\n" +
            "vlayehgxmozu\n" +
            "\n" +
            "khc\n" +
            "crkylh\n" +
            "ewticaxphkd\n" +
            "fhncmk\n" +
            "khcf\n" +
            "\n" +
            "ofvtnbpayduik\n" +
            "ufbiatxvpdoyn\n" +
            "oibfupdrtvyna\n" +
            "favdotpyixuqnb\n" +
            "ywatimcefbgvpsoundz\n" +
            "\n" +
            "ismcgzfqbxdlv\n" +
            "zlwdsivqcbgmf\n" +
            "szcbqidfgvlm\n" +
            "\n" +
            "fgjx\n" +
            "xjf\n" +
            "fxpjm\n" +
            "xjf\n" +
            "\n" +
            "etuipyaxvmjszkf\n" +
            "aeyjvuwzspkim\n" +
            "pajvmizekyus\n" +
            "\n" +
            "nmbyxzehsagcdfjvt\n" +
            "hzbaxdfyjevntgc\n" +
            "dvthajbznegxfcy\n" +
            "\n" +
            "ftwqrgzohp\n" +
            "hexzqdjsrfwmu\n" +
            "\n" +
            "eubmrcntqyxpsjozvilgadhkfw\n" +
            "zjfrdtwiuyoaepcnmkslqvgxbh\n" +
            "keiurfhgmzovydqapcxjswntbl\n" +
            "umkocxlwagfbzepjyirtvdsnhq\n" +
            "kngzxjrshovmdbtclwfiqepyua\n" +
            "\n" +
            "lyomqhdu\n" +
            "mylowqh\n" +
            "\n" +
            "chlwr\n" +
            "rhwcl\n" +
            "crlhw\n" +
            "wcplrfh\n" +
            "\n" +
            "tamkofzcpq\n" +
            "tomgsjqca\n" +
            "\n" +
            "bj\n" +
            "vfwbi\n" +
            "gb\n" +
            "gbz\n" +
            "\n" +
            "njaecfkliuwm\n" +
            "cnvkfwualmij\n" +
            "iaunwmfelckj\n" +
            "hjifcqxumnkalw\n" +
            "\n" +
            "iht\n" +
            "orlie\n" +
            "afsxupiz\n" +
            "\n" +
            "nocfkzrdstjqwu\n" +
            "ehisrtpqnwgaymbuc\n" +
            "\n" +
            "qxgt\n" +
            "gtoxcj\n" +
            "txgr\n" +
            "\n" +
            "hoxsgkdiqtfz\n" +
            "gtfisxozhvdk\n" +
            "gofksdtxihz\n" +
            "izghftsdokx\n" +
            "\n" +
            "i\n" +
            "x\n" +
            "a\n" +
            "i\n" +
            "i\n" +
            "\n" +
            "knqftuisvegdjw\n" +
            "ymogrc\n" +
            "yacpbrog\n" +
            "gxlp\n" +
            "\n" +
            "sa\n" +
            "k\n" +
            "k\n" +
            "w\n" +
            "b\n" +
            "\n" +
            "speodbqvngkjrl\n" +
            "nfslobmegdpkjvqr\n" +
            "rpgbneasdkljqvo\n" +
            "dnvklcgjiorqpubse\n" +
            "\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "y\n" +
            "\n" +
            "pahzx\n" +
            "axpz\n" +
            "axzp\n" +
            "\n" +
            "ya\n" +
            "a\n" +
            "ay\n" +
            "ta\n" +
            "\n" +
            "haposzk\n" +
            "lromwgtifpz\n" +
            "xobjpszq\n" +
            "pujonz\n" +
            "ndopyqvz\n" +
            "\n" +
            "wqfl\n" +
            "kwuqelft\n" +
            "lfbvwq\n" +
            "\n" +
            "cqgefyksvhwpalxdbrimoznu\n" +
            "spvyfeucqnigwxbkzrmadl\n" +
            "sxlwrdbyvgzpqmnuacfejti\n" +
            "\n" +
            "ou\n" +
            "uo\n" +
            "uo\n" +
            "ou\n" +
            "uo\n" +
            "\n" +
            "oridzvksnfuep\n" +
            "vsrpfexizdoq\n" +
            "\n" +
            "nxo\n" +
            "qgx\n" +
            "\n" +
            "xybutqfszdhl\n" +
            "ybsdlqfxutz\n" +
            "zlxuydqbtsf\n" +
            "\n" +
            "tl\n" +
            "tbla\n" +
            "rtel\n" +
            "jtgxlohyc\n" +
            "\n" +
            "w\n" +
            "vrgofi\n" +
            "kcjt\n" +
            "\n" +
            "xkqnrf\n" +
            "pxqnr\n" +
            "xrqn\n" +
            "qrxnp\n" +
            "qxrn\n" +
            "\n" +
            "pabnotufrs\n" +
            "bornptsda\n" +
            "sptobanru\n" +
            "mjzonarsplybgt\n" +
            "uranspoqbtx\n" +
            "\n" +
            "gncfptk\n" +
            "qyodies\n" +
            "\n" +
            "tiln\n" +
            "lt\n" +
            "lt\n" +
            "lt\n" +
            "\n" +
            "ecbxuofajgshqk\n" +
            "crehbqksaoifjux\n" +
            "klibxfuhqejocaws\n" +
            "csbxhojuatefkq\n" +
            "gjaqcexhkofbus\n" +
            "\n" +
            "egjflivrcywdtu\n" +
            "gyiedbfovxt\n" +
            "qsviadhygtef\n" +
            "gihexypfdvnt\n" +
            "\n" +
            "niotdwkarb\n" +
            "jbimonfkl\n" +
            "\n" +
            "j\n" +
            "z\n" +
            "\n" +
            "yfob\n" +
            "bymsrul\n" +
            "byqu\n" +
            "\n" +
            "dsycgzhtioxrpwvlen\n" +
            "edskiwvnhozrcypglt\n" +
            "\n" +
            "ygcjblprwkiehz\n" +
            "esfjghqbliczwpuk\n" +
            "ieghcjlpzkwmb\n" +
            "\n" +
            "mcephzsxawni\n" +
            "imazphsnexw\n" +
            "mxezwnhysipa\n" +
            "wsheabqmnipxzd\n" +
            "pcmwhysneazxi\n" +
            "\n" +
            "yovtlfcuiwxmskzjqeghr\n" +
            "gbcvlityzjxqmfoswkue\n" +
            "mqlgfwkvysjuzntieoxc\n" +
            "\n" +
            "hivam\n" +
            "amfuvi\n" +
            "aemv\n" +
            "mxahvg\n" +
            "\n" +
            "lze\n" +
            "le\n" +
            "lze\n" +
            "lepd\n" +
            "\n" +
            "jwpm\n" +
            "wjmc\n" +
            "gcmjw\n" +
            "mjdaw\n" +
            "jwm\n" +
            "\n" +
            "s\n" +
            "sxuq\n" +
            "su\n" +
            "ns\n" +
            "uqs\n" +
            "\n" +
            "csqmipzdnhxkvfgt\n" +
            "hxdfqvptigsmcn\n" +
            "snhpfmtgqivcxd\n" +
            "scihxqwpmdntfvg\n" +
            "\n" +
            "nrsmoa\n" +
            "rsnma\n" +
            "sramn\n" +
            "nasmr\n" +
            "msnar\n" +
            "\n" +
            "yihjeplactzrdfb\n" +
            "ztfekaljidry\n" +
            "\n" +
            "qwhty\n" +
            "gweh\n" +
            "zksdnuipmhal\n" +
            "oxtwrhcbjq\n" +
            "qhcvb\n" +
            "\n" +
            "ybemxa\n" +
            "jseoixkvc\n" +
            "ugdxepl\n" +
            "\n" +
            "tofhpsgaul\n" +
            "lqushgofp\n" +
            "lfphogsu\n" +
            "goplhsuf\n" +
            "lhsugpof\n" +
            "\n" +
            "gdwzk\n" +
            "xqw\n" +
            "\n" +
            "wmiagjvocxrzkhdtfu\n" +
            "xhwscvljdqryibpgofma\n" +
            "\n" +
            "rgacswftbpxydum\n" +
            "rsmtxdypgofuacwb\n" +
            "rwqkufstdjxmnalgbpyc\n" +
            "thzabcdwprgyxmsfu\n" +
            "caywrpsduftgxbvm\n" +
            "\n" +
            "dujpzvsb\n" +
            "jusdvpabr\n" +
            "odvjbsup\n" +
            "budpvjs\n" +
            "kpujbsvd\n" +
            "\n" +
            "gfpncwmjrdlx\n" +
            "rwmcfnbdplgj\n" +
            "\n" +
            "djw\n" +
            "jdw\n" +
            "wjd\n" +
            "diwvjn\n" +
            "jwdb\n" +
            "\n" +
            "h\n" +
            "k\n" +
            "z\n" +
            "k\n" +
            "v\n" +
            "\n" +
            "al\n" +
            "lpa\n" +
            "la\n" +
            "\n" +
            "chinjymkwe\n" +
            "vnwgcemkp\n" +
            "kvcemyxnj\n" +
            "enkcm\n" +
            "krlceuqnfom\n" +
            "\n" +
            "glewafm\n" +
            "ngqawfvul\n" +
            "\n" +
            "fia\n" +
            "rup\n" +
            "j\n" +
            "rmp\n" +
            "ju\n" +
            "\n" +
            "dgvtfbxow\n" +
            "wvtjgbdxf\n" +
            "gxtbwvd\n" +
            "tbndgxzqvw\n" +
            "\n" +
            "kuycgeanqwh\n" +
            "unkhyceqgaw\n" +
            "aykcweqguhn\n" +
            "ceqhwkunyag\n" +
            "\n" +
            "vcighoudqlamkrt\n" +
            "dnyhemguilvqtao\n" +
            "hxzoubfvgiqajtlwm\n" +
            "ovqepnmgladtihu\n" +
            "oatnlremuvsigqh\n" +
            "\n" +
            "nd\n" +
            "wdn\n" +
            "xnea\n" +
            "ribpvsfynoctmqh\n" +
            "n\n" +
            "\n" +
            "rpflnskacoq\n" +
            "laqojrp\n" +
            "liprwqao\n" +
            "aojlprq\n" +
            "oarqipl\n" +
            "\n" +
            "jvk\n" +
            "zwmvj\n" +
            "jv\n" +
            "vj\n" +
            "\n" +
            "vydxlwk\n" +
            "vxywd\n" +
            "xdyzurw\n" +
            "\n" +
            "lqghripoewbjdvy\n" +
            "qbpcdjlwhovrey\n" +
            "pledvrqbwhsojanf\n" +
            "hjqdbptlmwzeogvr\n" +
            "rqjwohdipuvble\n" +
            "\n" +
            "h\n" +
            "h\n" +
            "\n" +
            "ot\n" +
            "t\n" +
            "t\n" +
            "\n" +
            "fyxkdhnwalez\n" +
            "weakhydnlxzf\n" +
            "\n" +
            "xhqawsrol\n" +
            "guxblwar\n" +
            "lvkjrydiwxmptea\n" +
            "wfaxnrgl\n" +
            "\n" +
            "famd\n" +
            "xmd\n" +
            "md\n" +
            "fmd\n" +
            "damj\n" +
            "\n" +
            "istm\n" +
            "smbj\n" +
            "mwbs\n" +
            "msw\n" +
            "ms\n" +
            "\n" +
            "raszvfpwdmeich\n" +
            "awfmvlizcperdh\n" +
            "pjviuhacmzfwdryqe\n" +
            "\n" +
            "t\n" +
            "t\n" +
            "t\n" +
            "t\n" +
            "t\n" +
            "\n" +
            "b\n" +
            "b\n" +
            "\n" +
            "uemjsklzft\n" +
            "teukljfmzs\n" +
            "ztfjulsemk\n" +
            "jkfesztmlu\n" +
            "jlumszeftk\n" +
            "\n" +
            "toczuxmkslrhpvijeg\n" +
            "mopultekcxzv\n" +
            "xukmoedpltczva\n" +
            "kpolveuzxmtc\n" +
            "pktdovemcxzul\n" +
            "\n" +
            "agvfm\n" +
            "jvogqfiau\n" +
            "vdaogf\n" +
            "\n" +
            "c\n" +
            "gqd\n" +
            "\n" +
            "sgfpy\n" +
            "sgfbpl\n" +
            "\n" +
            "jretxvqmfghp\n" +
            "tureqgfvjm\n" +
            "ijtyqezrgvnfml\n" +
            "mergqtjfv\n" +
            "\n" +
            "ubzsrptcgxwdoe\n" +
            "tebrzfpwuxgds\n" +
            "wbdrxtfpgsuez\n" +
            "gvnuhzpdebwaxtrs\n" +
            "\n" +
            "gdqmje\n" +
            "gqtcpdmfe\n" +
            "rxqyiehnogmsbdv\n" +
            "\n" +
            "fqwzlinbormheg\n" +
            "mjorlniezb\n" +
            "\n" +
            "ia\n" +
            "ai\n" +
            "ia\n" +
            "ai\n" +
            "\n" +
            "xghswfuabdlqicnyekmt\n" +
            "bgetcxwalnkdiysfuh\n" +
            "sigwankrfuhtcxedlby\n" +
            "nlwxfucbhgtdseikya\n" +
            "khawdecfngultbyixs\n" +
            "\n" +
            "cwzgvbuqlsyetoiajnpm\n" +
            "asjpbudkhoinqgtzryfwevxc\n" +
            "\n" +
            "zbpfxictqy\n" +
            "udpyqtxizcgef\n" +
            "zptxicfhqy\n" +
            "hpqcfbzixyt\n" +
            "zxhqpyftic\n" +
            "\n" +
            "oirypkjhxfcwdqeagu\n" +
            "hwoqyupdrjigbmvxsa\n" +
            "kxdhpangqieuroyjw\n" +
            "\n" +
            "fegnzr\n" +
            "rzfgne\n" +
            "erfnzg\n" +
            "znfreg\n" +
            "\n" +
            "pvuafthmr\n" +
            "dvpmwcyg\n";
}
